WIDTH = 1000
HEIGHT = 1000
TICKS = 1000
GENERATIONS_TO_RUN = 5


POPULATION_SIZE = 100
MUTATION_RATE = 0.001
CROSSOVER_RATE = 0.7

CREATURE_INITIAL_ENERGY = 500
# CREATURE_INITIAL_SENSE = 80

INITIAL_ENERGY_FROM_FOOD = 50
MAX_FOOD_ON_SCREEN = 200
CHANCE_FOR_FOOD_TO_SPAWN_AT_TICK = 1
FOOD_SIZE = 2

INITIAL_SIZE_LOWER_BOUND = 1
INITIAL_SIZE_UPPER_BOUND = 21

INITIAL_SPEED_LOWER_BOUND = 3
INITIAL_SPEED_UPPER_BOUND = 10

INITIAL_SENSE_LOWER_BOUND = 10
INITIAL_SENSE_UPPER_BOUND = 200