WIDTH = 1400
HEIGHT = 800
TICKS = 1500
GENERATIONS_TO_RUN = 20


POPULATION_SIZE = 200
MUTATION_RATE = 0.07
CROSSOVER_RATE = 0.7

CREATURE_INITIAL_ENERGY = 500
# CREATURE_INITIAL_SENSE = 80

INITIAL_ENERGY_FROM_FOOD = 50
MAX_FOOD_ON_SCREEN = 200
CHANCE_FOR_FOOD_TO_SPAWN_AT_TICK = 1
FOOD_SIZE = 2
NUM_FOOD_TO_SPAWN_AT_TICK = 1

INITIAL_SIZE_LOWER_BOUND = 1
INITIAL_SIZE_UPPER_BOUND = 21

INITIAL_SPEED_LOWER_BOUND = 2
INITIAL_SPEED_UPPER_BOUND = 20

INITIAL_SENSE_LOWER_BOUND = 10
INITIAL_SENSE_UPPER_BOUND = 200

# They had MASSIVE sense ranges, but one guy had a huge sense range and was also really fast. 
# I think our code doesn't prevent them from having both big sense range and being fast, it only makes them decrease slightly